name: omairqazi-instantnews
version: '1.2.4'
summary: https://github.com/shivam043/instantnews
description: |
  Get live news instantly
grade: stable
confinement: strict
apps:
  instantnews:
    command: instantnews
    plugs: [network]
parts:
  instantnews:
    source: https://github.com/shivam043/instantnews.git
    source-commit: de233b38a7ed8a6ed440e1700f02c1ef65f581a7
    plugin: python
